const DEVIL_COMMENTS = {
  bands: [
    { min: 0.95, key: 'almostCertain'    },
    { min: 0.80, key: 'favourable'       },
    { min: 0.60, key: 'evenOdds'         },
    { min: 0.40, key: 'balanced'         },
    { min: 0.20, key: 'unfavourable'     },
    { min: 0.05, key: 'dire'             },
    { min: 0.00, key: 'almostImpossible' },
  ],
  main: {
    almostCertain: {
      shared: [
        "The outcome is all but assured.",
        "The terms strongly favour success.",
        "Proceed. The odds are acceptable.",
        "Only remarkable incompetence should prevent success.",
        "Consider this matter settled.",
        "I would not normally waste ink on such certainties.",
        "Failure here would constitute a breach of natural law.",
        "Such odds rarely require my expertise.",
        "Exceptional outcomes are surprisingly common.",
        "Excellence is well represented in this projection.",
        "Expect fortune to exceed expectations.",
      ],
      pf: [
        "Abadar himself would approve these figures.",
        "The dice favour you today.",
        "Your training shows.",
        "Your preparation represents a sound investment.",
        "Desna smiles upon these numbers.",
        "Pharasma has not yet opened your file.",
        "The gods of fate have already drafted the conclusion.",
      ],
      sf: [
        "Prediction confidence: 99.2%.",
        "Recommended course confirmed.",
        "Outcome variance is negligible.",
        "Proceed.",
        "Statistical certainty achieved.",
        "Drift calculations complete.",
        "Simulation converged.",
        "Triune approves this projection.",
        "All sensor arrays confirm viability.",
        "Model consensus: proceed.",
        "Aetheric analysis complete.",
      ],
    },
    favourable: {
      shared: [
        "A prudent investment.",
        "This bargain favours you.",
        "The risk is modest.",
        "Most such ventures conclude successfully.",
        "Your preparation has measurable value.",
        "The terms are acceptable.",
        "I have drafted worse agreements.",
        "The margin remains comfortable.",
        "You have negotiated well.",
      ],
      pf: [
        "Abadar himself would approve these figures.",
        "The dice favour you today.",
        "Your training shows.",
        "Your preparation represents a sound investment.",
      ],
      sf: [
        "Probability favours execution.",
        "Expected value is positive.",
        "Risk remains within operational limits.",
        "Resource expenditure justified.",
        "Mission viability confirmed.",
        "Simulation converged.",
        "Risk matrix within tolerance.",
      ],
    },
    evenOdds: {
      shared: [
        "Success remains the more likely outcome.",
        "The contract remains unsigned.",
        "Fortune may yet require persuasion.",
        "A calculated risk.",
        "An acceptable wager.",
        "The ink has not yet dried.",
        "History favours the prepared.",
        "I have witnessed less promising ventures succeed.",
        "Marginally preferable to the alternative.",
      ],
      pf: [],
      sf: [
        "Outcome remains stochastic.",
        "Additional variables recommended.",
        "Current data is inconclusive.",
        "Prediction confidence remains moderate.",
        "Simulation incomplete.",
      ],
    },
    balanced: {
      shared: [
        "The scales remain balanced.",
        "This agreement could favour either party.",
        "Neither success nor failure has established precedence.",
        "The ledger remains open.",
        "Further advantage is advisable.",
        "The consequences are disproportionate.",
        "The clause is contested.",
        "I would seek better terms before signing.",
        "Tip the scales. You have time.",
        "This is precisely the sort of contract that keeps my profession busy.",
      ],
      pf: [],
      sf: [
        "Outcome remains stochastic.",
        "Current data is inconclusive.",
        "Prediction confidence remains moderate.",
      ],
    },
    unfavourable: {
      shared: [
        "The balance shifts against you.",
        "The penalties outweigh the rewards.",
        "Additional preparation is recommended.",
        "This contract carries expensive consequences.",
        "Proceed only if necessity demands.",
        "Catastrophic error remains a significant possibility.",
        "One poor decision could prove decisive.",
        "The consequences are disproportionate.",
        "I would not countersign this agreement.",
        "The breach clause carries considerable weight.",
        "A renegotiation is strongly advised.",
        "Such odds carry what we call acceptable losses — for the other party.",
      ],
      pf: [],
      sf: [
        "Projected losses exceed acceptable thresholds.",
        "Mission risk increasing.",
        "Recommendation: reconsider.",
        "Outcome confidence deteriorating.",
        "Success probability declining.",
        "Sensor models indicate elevated risk.",
        "Quantum variance exceeds tolerance.",
        "The data does not support your optimism.",
        "This projection has been flagged for review.",
      ],
    },
    dire: {
      shared: [
        "I would decline these terms.",
        "The likelihood of catastrophe is substantial.",
        "Your confidence exceeds the evidence.",
        "Few survive such calculations.",
        "I would require considerable compensation.",
        "Catastrophic error remains a significant possibility.",
        "One poor decision could prove decisive.",
        "The consequences are disproportionate.",
        "I charge considerably more for outcomes this uncertain.",
        "Success is possible. It is merely improbable.",
        "You have mistaken optimism for strategy.",
        "I have witnessed braver decisions. The outcomes were instructive.",
      ],
      pf: [
        "Even Cayden would hesitate.",
        "The River of Souls has taken notice.",
        "The Lady of Graves may soon receive another petitioner.",
        "You rely upon miracles, not mathematics.",
        "Pharasma has already prepared your case.",
        "I have advised petitioners with better odds than this. They are now petitioners.",
      ],
      sf: [
        "Projected losses exceed acceptable thresholds.",
        "Recommendation: reconsider.",
        "Sensor models indicate elevated risk.",
        "Quantum variance exceeds tolerance.",
        "Probability lattice collapsing.",
        "Abort recommended.",
        "Mission failure predicted.",
        "Outcome classified as improbable.",
        "Statistical outlier required.",
        "Proceeding would be irrational.",
        "Core systems recommend abort.",
        "Recommendation logged. Ignored.",
      ],
    },
    almostImpossible: {
      shared: [
        "The outcome is effectively predetermined.",
        "Failure has already signed this agreement.",
        "Only extraordinary fortune alters this conclusion.",
        "These terms are unacceptable.",
        "Even I would not draft this contract.",
        "The mathematics do not support your ambition.",
        "This is not a contract. It is a confession.",
        "I will prepare the documentation for the alternative outcome.",
        "Should you succeed, I will revise my models entirely.",
        "I would note for the record that I advised against this.",
      ],
      pf: [
        "Even Cayden would hesitate.",
        "The River of Souls has taken notice.",
        "The Lady of Graves may soon receive another petitioner.",
        "You rely upon miracles, not mathematics.",
        "Not even Iomedae would take this contract.",
        "Asmodeus would decline to countersign.",
      ],
      sf: [
        "Abort recommended.",
        "Mission failure predicted.",
        "Outcome classified as improbable.",
        "Statistical outlier required.",
        "Proceeding would be irrational.",
        "No predictive model supports success.",
        "Probability lattice collapsing.",
        "Scenario analysis complete. All outcomes unfavourable.",
      ],
    },
  },
};
